# Generated by Django 5.2.16 on 2026-07-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'TipoSabor',
                'verbose_name_plural': 'Tipos de Sabor',
            },
        ),
        migrations.AlterModelOptions(
            name='embalagem',
            options={'verbose_name': 'Embalagem', 'verbose_name_plural': 'Embalagens'},
        ),
    ]
