# Generated by Django 5.2.16 on 2026-07-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tiposabor_alter_embalagem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposabor',
            options={'verbose_name': 'Sabor', 'verbose_name_plural': 'Sabores'},
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_sabor', to='myapp.tiposabor')),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
            },
        ),
    ]
