# Generated by Django 5.2.16 on 2026-07-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_tiposabor_options_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': '4. Coberturas',
            },
        ),
        migrations.AlterModelOptions(
            name='embalagem',
            options={'verbose_name': 'Embalagem', 'verbose_name_plural': '1. Embalagens'},
        ),
        migrations.AlterModelOptions(
            name='sabor',
            options={'verbose_name': 'Sabor', 'verbose_name_plural': '3. Sabores'},
        ),
        migrations.AlterModelOptions(
            name='tiposabor',
            options={'verbose_name': 'Tipo de sabor', 'verbose_name_plural': '2. Tipos de sabor'},
        ),
    ]
