# Generated by Django 5.2.16 on 2026-07-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cobertura_alter_embalagem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontaPote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(null=True)),
                ('cobertura', models.ManyToManyField(to='myapp.cobertura')),
                ('embalagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embalagem', to='myapp.embalagem')),
            ],
            options={
                'verbose_name': 'Montar Pote',
                'verbose_name_plural': 'Montar Potes',
            },
        ),
        migrations.CreateModel(
            name='SelSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bolas', models.PositiveIntegerField()),
                ('pote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pote', to='myapp.montapote')),
                ('sabor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabor', to='myapp.sabor')),
            ],
            options={
                'verbose_name': 'Selecionar Sabor',
                'verbose_name_plural': 'Selecionar Sabores',
            },
        ),
    ]
