# Generated by Django 5.2.16 on 2026-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_montapote_selsabor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montapote',
            options={'verbose_name': 'Montar Pote', 'verbose_name_plural': 'b. Montar Potes'},
        ),
        migrations.AlterModelOptions(
            name='selsabor',
            options={'verbose_name': 'Selecionar Sabor', 'verbose_name_plural': 'a. Selecionar Sabores'},
        ),
        migrations.CreateModel(
            name='SacolaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('potes', models.ManyToManyField(to='myapp.montapote')),
            ],
            options={
                'verbose_name': 'C - Carrinho',
                'verbose_name_plural': 'C - Carrinho',
            },
        ),
    ]
