# Generated by Django 5.2.16 on 2026-07-27 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_montapote_options_alter_selsabor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sacolaitens',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'c. Carrinho'},
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
                ('pago', models.BooleanField()),
                ('itens_da_sacola', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sacolaitens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'd. Pedido',
            },
        ),
    ]
